---
#-----------------------------------
# Copyright IBM Corp. 1992, 2017. All rights reserved.
# US Government Users Restricted Rights - Use, duplication or disclosure
# restricted by GSA ADP Schedule Contract with IBM Corp.
#-----------------------------------

- include_vars: "{{ RC_PLAY_TOP }}/AWS/AWS-config.yml"

- include: start_ec2_node.yml
