---
# -----------------------------------
#  Copyright IBM Corp. 1992, 2018. All rights reserved.
#  US Government Users Restricted Rights - Use, duplication or disclosure
#  restricted by GSA ADP Schedule Contract with IBM Corp.
# -----------------------------------

- name: Prepare the first LSF EC2 node 
  debug:
    msg: "Ansible OS is {{ ansible_os_family }}"

- name: Install Package Dependencies for LSF
  package:
    name: "{{ item }}"
    state: latest
  with_items:
    - lsof
    - which
    - nfs-utils
    - strace
    - traceroute
    - wireshark
    - createrepo
  when: ansible_os_family == "RedHat"

- name: Check for existing authorized_keys
  stat:
    path: /root/authorized_keys
  register: have_authorized_keys

- name: Copy ssh key from deployer
  copy:
    src: files/id_rsa.pub
    dest: /root/authorized_keys
  when: have_authorized_keys.stat.exists == False

- name: Update Authoried Keys
  shell: cat /root/authorized_keys >> /root/.ssh/authorized_keys
  when: have_authorized_keys.stat.exists == False

- name: Reconfigure SSH
  lineinfile:
    dest: /etc/ssh/sshd_config
    backrefs: yes
    regexp: '^(PasswordAuthentication).*'
    line: '\1 yes'

- name: Restart Sshd
  systemd:
    name: sshd
    state: restarted

